version: '3.8'
services:
  db:
    image: postgres:16
    container_name: tienda_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=grafiti_color 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1475
    ports:
      - "5432:5432"

  # Servicio de la aplicación Django
  web:
    build: .
    container_name: tienda_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=grafiti_color 
      - DB_USER=postgres
      - DB_PASSWORD=1475
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: